Repository DeebotUniverse/client.py, pull requests merged in 2023-07, with the labels that each got.

#270 pin asyncio-mqtt to 0.16.1
  requirements.txt
Labels: pr: bugfix

#277 use taskgroup
  .pre-commit-config.yaml
  deebot_client/command.py
  deebot_client/events/event_bus.py
  deebot_client/map.py
  pylintrc
  setup.py
Labels: pr: refactor

#275 update and rename asyncio-mqtt to aiomqtt
  deebot_client/mqtt_client.py
  requirements.txt
  tests/conftest.py
  tests/fixtures/base.py
  tests/fixtures/mqtt_server.py
  tests/test_mqtt_client.py
Labels: pr: bugfix

#278 fire MapChangedEvent on map changes
  deebot_client/events/map.py
  deebot_client/map.py
  deebot_client/util.py
  tests/test_map.py
Labels: pr: new-feature

#280 map: fix divide-by-zero in dashed_line renderer
  deebot_client/map.py
Labels: pr: bugfix

#284 MapChangedEvent needs debounce and not throttle
  deebot_client/events/event_bus.py
  deebot_client/events/map.py
  deebot_client/map.py
  tests/events/test_event_bus.py
  tests/test_map.py
Labels: pr: refactor

#285 improve event_bus debounce
  deebot_client/events/event_bus.py
  tests/events/test_event_bus.py
  tests/test_map.py
Labels: pr: refactor

#281 change speed type of FanSpeedEvent
  deebot_client/commands/fan_speed.py
  deebot_client/events/__init__.py
  deebot_client/events/fan_speed.py
  tests/commands/test_fan_speed.py
Labels: pr: Breaking Change
