Repository DeebotUniverse/client.py, pull requests merged in 2023-12, with the labels that each got.

#367 Move assert_command outside of json
  tests/commands/__init__.py
  tests/commands/json/__init__.py
  tests/commands/json/test_charge.py
  tests/commands/json/test_clean_log.py
  tests/commands/json/test_custom.py
  tests/commands/json/test_map.py
Labels: pr: refactor

#368 Refactor message
  deebot_client/command.py
  deebot_client/commands/json/clean_count.py
  deebot_client/commands/json/common.py
  deebot_client/commands/json/efficiency.py
  deebot_client/commands/json/error.py
  deebot_client/commands/json/fan_speed.py
  deebot_client/commands/json/volume.py
  deebot_client/commands/json/water_info.py
  deebot_client/commands/json/work_mode.py
  deebot_client/message.py
  tests/commands/json/test_work_mode.py
Labels: pr: refactor

#370 Add Deebot T10 Omni
  deebot_client/hardware/deebot/lx3j7m.py
Labels: pr: new-feature

#371 Add Deebot (T|N)10 models
  deebot_client/hardware/deebot/626v6g.py
  deebot_client/hardware/deebot/clojes.py
  deebot_client/hardware/deebot/rss8xk.py
  deebot_client/hardware/deebot/umwv6z.py
  deebot_client/hardware/deebot/zjavof.py
Labels: pr: new-feature

#373 Use vector based graphic (SVG) for map rendering
  deebot_client/map.py
  requirements.txt
  tests/test_map.py
Labels: pr: enhancement

#378 Update ruff
  .pre-commit-config.yaml
  deebot_client/message.py
  tests/helpers/__init__.py
Labels: pr: dependency-update

#375 Reduce map svg size
  deebot_client/map.py
  pyproject.toml
  tests/test_map.py
Labels: pr: refactor

#379 Fix map reset changed
  deebot_client/map.py
Labels: pr: bugfix

#381 Remove unused map width
  deebot_client/map.py
Labels: pr: refactor

#382 Return None instead of a empty svg
  deebot_client/map.py
Labels: pr: refactor
