Repository DeebotUniverse/client.py, pull requests merged in 2024-01, with the labels that each got.

#384 Add capabilities for Deebot X1 Turbo
  deebot_client/hardware/deebot/2o4lnm.py
  pyproject.toml
  tests/hardware/test_init.py
Labels: pr: new-feature

#390 Log event name on already refresh log entry
  deebot_client/event_bus.py
Labels: pr: refactor

#369 Add xml GetError
  deebot_client/commands/json/error.py
  deebot_client/commands/xml/__init__.py
  deebot_client/commands/xml/common.py
  deebot_client/commands/xml/error.py
  deebot_client/const.py
  deebot_client/message.py
  tests/commands/json/test_error.py
  tests/commands/xml/__init__.py
  tests/commands/xml/test_error.py
Labels: pr: new-feature

#392 Automatically get continent from country
  .pre-commit-config.yaml
  README.md
  deebot_client/authentication.py
  deebot_client/models.py
  deebot_client/mqtt_client.py
  deebot_client/util/__init__.py
  deebot_client/util/continents.py
  tests/util/__init__.py
  tests/util/test_continents.py
  tests/util/test_init.py
Labels: pr: refactor

#393 Return eco-legacy devices on get_devices
  deebot_client/api_client.py
  deebot_client/models.py
Labels: pr: refactor

#396 Lower continents
  deebot_client/util/continents.py
  tests/util/test_continents.py
Labels: pr: bugfix

#398 Convert total stats time from seconds to minutes
  deebot_client/commands/json/stats.py
  tests/commands/json/test_stats.py
Labels: pr: Breaking Change

#400 Bump ruff to 1.14
  .pre-commit-config.yaml
Labels: pr: dependency-update

#399 Refactor map subscription
  deebot_client/event_bus.py
  deebot_client/map.py
  tests/common.py
  tests/conftest.py
  tests/test_map.py
Labels: pr: Breaking Change

#403 Add support for overriding urls and refactor configuration
  README.md
  deebot_client/authentication.py
  deebot_client/configuration.py
  deebot_client/const.py
  deebot_client/models.py
  deebot_client/mqtt_client.py
  deebot_client/util/continents.py
  tests/conftest.py
  tests/test_authentication.py
  tests/test_configuration.py
  tests/test_mqtt_client.py
  tests/test_mqtt_client_reconnect.py
Labels: pr: Breaking Change

#404 Update no capabilities log entry
  deebot_client/hardware/deebot/__init__.py
Labels: pr: refactor

#406 Make sure country is uppercase
  deebot_client/configuration.py
  deebot_client/util/continents.py
Labels: pr: bugfix

#409 Split config and add posibility to disable mqtt ssl context validation
  deebot_client/authentication.py
  deebot_client/configuration.py
  deebot_client/mqtt_client.py
  pyproject.toml
  tests/conftest.py
  tests/test_authentication.py
  tests/test_configuration.py
  tests/test_mqtt_client.py
  tests/test_mqtt_client_reconnect.py
Labels: pr: Breaking Change

#413 Rename mqtt config + arguments
  README.md
  deebot_client/authentication.py
  deebot_client/const.py
  deebot_client/mqtt_client.py
  tests/conftest.py
  tests/test_authentication.py
  tests/test_mqtt_client.py
Labels: pr: refactor
