Repository DeebotUniverse/client.py, pull requests merged in 2024-05, with the labels that each got.

#483 Fix map subset parsing on newer bots
  deebot_client/commands/json/map.py
  deebot_client/map.py
  tests/commands/__init__.py
  tests/commands/json/test_map.py
  tests/test_map.py
Labels: pr: bugfix

#490 Update error codes
  deebot_client/const.py
Labels: pr: enhancement

#497 Add support for GOAT G1 800 (White)
  deebot_client/hardware/deebot/guzput.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#489 Add DEEBOT T10 TURBO
  deebot_client/hardware/deebot/9s1s80.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#505 Fix getError
  deebot_client/commands/json/error.py
  tests/commands/json/test_error.py
Labels: pr: bugfix

#494 Add 4 more Lifespan entities
  deebot_client/events/__init__.py
  tests/commands/json/test_life_span.py
Labels: pr: enhancement

#506 GOAT GX-600 support added
  deebot_client/hardware/deebot/2ap5uq.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#514 Add cut direction for lawn mower goat g1
  deebot_client/capabilities.py
  deebot_client/commands/json/__init__.py
  deebot_client/commands/json/cut_direction.py
  deebot_client/events/__init__.py
  deebot_client/hardware/deebot/5xu9h3.py
  tests/commands/json/test_cut_direction.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#513 Add command response
  deebot_client/command.py
  deebot_client/commands/json/clean.py
  deebot_client/device.py
  deebot_client/event_bus.py
  deebot_client/map.py
  tests/commands/__init__.py
  tests/commands/json/test_common.py
  tests/test_command.py
  tests/test_device.py
Labels: pr: new-feature

#433 Align viewbox center with vacuum map center
  deebot_client/map.py
  tests/test_map.py
Labels: pr: refactor
