Repository DeebotUniverse/client.py, pull requests merged in 2024-04, with the labels that each got.

#457 Add xml command "GetFanSpeed"
  deebot_client/commands/xml/__init__.py
  deebot_client/commands/xml/fan_speed.py
  tests/commands/xml/test_fan_speed.py
Labels: pr: new-feature

#468 Update pre-commit checks
  .pre-commit-config.yaml
Labels: pr: dependency-update

#467 Use IntEnum instead of DisplayNameIntEnum for CleanJobStatus
  deebot_client/events/__init__.py
  tests/commands/json/test_clean_log.py
Labels: pr: Breaking Change

#469 Remove DisplayNameIntEnum
  deebot_client/commands/json/efficiency.py
  deebot_client/commands/json/fan_speed.py
  deebot_client/commands/json/water_info.py
  deebot_client/commands/json/work_mode.py
  deebot_client/events/__init__.py
  deebot_client/events/efficiency_mode.py
  deebot_client/events/fan_speed.py
  deebot_client/events/water_info.py
  deebot_client/events/work_mode.py
  deebot_client/util/__init__.py
  tests/commands/json/test_efficiency.py
  tests/commands/json/test_fan_speed.py
  tests/commands/json/test_water_info.py
  tests/commands/json/test_work_mode.py
  tests/events/test_water_info.py
  tests/helpers/__init__.py
Labels: pr: Breaking Change

#471 Add support for X2 Omni
  deebot_client/hardware/deebot/lf3bn4.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#473 Fix blocking call to import_module inside the event loop
  deebot_client/api_client.py
  deebot_client/hardware/deebot/__init__.py
  tests/conftest.py
  tests/hardware/test_init.py
Labels: pr: bugfix

#472 Add support for X2 Omni
  deebot_client/hardware/deebot/e6ofmn.py
  deebot_client/hardware/deebot/lf3bn4.py
  tests/hardware/test_init.py
Labels: pr: new-feature
