Repository DeebotUniverse/client.py, pull requests merged in 2024-08, with the labels that each got.

#550 Bump aiohttp to 3.10
  .pre-commit-config.yaml
  deebot_client/authentication.py
  deebot_client/exceptions.py
  requirements.txt
  tests/test_command.py
Labels: pr: dependency-update

#548 Add Deebot T30 Omni
  deebot_client/hardware/deebot/z4lvk7.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#554 Add CleanAreaV2
  deebot_client/commands/json/clean.py
  deebot_client/hardware/deebot/kr0277.py
  tests/commands/json/test_clean.py
Labels: pr: new-feature

#557 Create ssl default context only if needed
  deebot_client/mqtt_client.py
Labels: pr: bugfix
