Repository DeebotUniverse/client.py, pull requests merged in 2024-12, with the labels that each got.

#608 Add Deebot N20 Pro Plus
  deebot_client/hardware/deebot/qhe2o2.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#617 Add support for Deebot N8 Pro+
  deebot_client/hardware/deebot/ifbw08.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#618 Add support for Deebot T10
  deebot_client/hardware/deebot/jtmf04.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#619 Add support for Deebot N8 Pro+ Black
  deebot_client/hardware/deebot/85as7h.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#611 Add X1 Omni support (1vxt52)
  deebot_client/hardware/deebot/1vxt52.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#622 adding Deebot N30 Omni support (zwkcqc)
  deebot_client/hardware/deebot/zwkcqc.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#624 Add Deebot OZMO T9 AIVI
  deebot_client/hardware/deebot/659yh8.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#625 Add Ozmo T8G support (b742vd)
  deebot_client/hardware/deebot/b742vd.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#628 Add Support for Deebot N8+
  deebot_client/hardware/deebot/7bryc5.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#631 Optimize CI
  .github/workflows/ci.yml
  mypy.ini
Labels: pr: refactor

#630 Add support for Deebot T9 AIVI (8kwdb4)
  deebot_client/hardware/deebot/8kwdb4.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#632 Added support for T9 PLUS (um2ywg)
  deebot_client/hardware/deebot/um2ywg.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#659 Add Deebot X5 Pro Omni (lr4qcs)
  deebot_client/hardware/deebot/lr4qcs.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#638 Add old Support for Ozmo T8
  deebot_client/hardware/deebot/h18jkh.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#658 Add DEEBOT OZMO T8 AIVI+ (w16crm)
  deebot_client/hardware/deebot/w16crm.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#656 added support for Deebot X1 Plus (n4gstt)
  deebot_client/hardware/deebot/n4gstt.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#653 Add support for Deebot N7 (r5zxjr)
  deebot_client/hardware/deebot/r5zxjr.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#623 Add Deebot U2 Pro
  deebot_client/hardware/deebot/7j1tu6.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#639 Add Deebot OZMO T8+
  deebot_client/hardware/deebot/fqxoiu.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#650 Added T20e Omni (py3qif)
  deebot_client/hardware/deebot/py3qif.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#649 Added DEEBOT T9 (ucn2xe)
  deebot_client/hardware/deebot/ucn2xe.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#641 Add Deebot OZMO T8 Pure (0bdtzz)
  deebot_client/hardware/deebot/0bdtzz.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#637 Add Support for Deebot N8 Pro
  deebot_client/hardware/deebot/snxbvc.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#666 Add 24 similar models
  deebot_client/hardware/deebot/12baap.py
  deebot_client/hardware/deebot/1b23du.py
  deebot_client/hardware/deebot/36xnxf.py
  deebot_client/hardware/deebot/3w7j5e.py
  deebot_client/hardware/deebot/7piq03.py
  deebot_client/hardware/deebot/822x8d.py
  deebot_client/hardware/deebot/c0lwyn.py
  deebot_client/hardware/deebot/d4v1pm.py
  deebot_client/hardware/deebot/edoodo.py
  deebot_client/hardware/deebot/gwtll7.py
  deebot_client/hardware/deebot/lhbd50.py
  deebot_client/hardware/deebot/n6cwdb.py
  deebot_client/hardware/deebot/nq9yhl.py
  deebot_client/hardware/deebot/o0a4ju.py
  deebot_client/hardware/deebot/p0l0af.py
  deebot_client/hardware/deebot/r5y7re.py
  deebot_client/hardware/deebot/rvflzn.py
  deebot_client/hardware/deebot/tlthqk.py
  deebot_client/hardware/deebot/u4h1uk.py
  deebot_client/hardware/deebot/u6eqoa.py
  deebot_client/hardware/deebot/w7k3yc.py
  deebot_client/hardware/deebot/y2qy3m.py
  deebot_client/hardware/deebot/yinacl.py
  deebot_client/hardware/deebot/yu362x.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#667 Add DEEBOT Neo (z0gd1j)
  deebot_client/hardware/deebot/z0gd1j.py
Labels: pr: new-feature

#662 Add support for T30S Pro Omni
  deebot_client/hardware/deebot/xco2fc.py
Labels: pr: new-feature

#665 Add DEEBOT T8 AIVI (bs40nz)
  deebot_client/hardware/deebot/bs40nz.py
Labels: pr: new-feature

#663 Add support for Deebot N30 pro Omni (87swps)
  deebot_client/hardware/deebot/87swps.py
Labels: pr: new-feature

#673 Add support for Deebot N10
  deebot_client/hardware/deebot/m1wkuw.py
Labels: pr: new-feature

#675 Add models by similarity
  deebot_client/hardware/deebot/9kpees.py
  deebot_client/hardware/deebot/cb69w5.py
  deebot_client/hardware/deebot/dlrbzq.py
  deebot_client/hardware/deebot/i35yb6.py
Labels: pr: new-feature

#679 Add X5 OMNI support (4jd37g)
  deebot_client/hardware/deebot/4jd37g.py
Labels: pr: new-feature

#691 Pin to 3.13.0 until Pylint solve the issue
  .python-version
Labels: pr: bugfix

#686 Add Deebot N8 Black (7zya6u)
  deebot_client/hardware/deebot/7zya6u.py
Labels: pr: new-feature

#680 Add DEEBOT T8 MAX (7n95dm)
  deebot_client/hardware/deebot/7n95dm.py
Labels: pr: new-feature

#694 Replace deprecated class properties
  deebot_client/command.py
  deebot_client/commands/json/__init__.py
  deebot_client/commands/json/advanced_mode.py
  deebot_client/commands/json/battery.py
  deebot_client/commands/json/border_switch.py
  deebot_client/commands/json/carpet.py
  deebot_client/commands/json/charge.py
  deebot_client/commands/json/charge_state.py
  deebot_client/commands/json/child_lock.py
  deebot_client/commands/json/clean.py
  deebot_client/commands/json/clean_count.py
  deebot_client/commands/json/clean_logs.py
  deebot_client/commands/json/clean_preference.py
  deebot_client/commands/json/clear_map.py
  deebot_client/commands/json/common.py
  deebot_client/commands/json/continuous_cleaning.py
  deebot_client/commands/json/cross_map_border_warning.py
  deebot_client/commands/json/custom.py
  deebot_client/commands/json/cut_direction.py
  deebot_client/commands/json/efficiency.py
  deebot_client/commands/json/error.py
  deebot_client/commands/json/fan_speed.py
  deebot_client/commands/json/life_span.py
  deebot_client/commands/json/map.py
  deebot_client/commands/json/moveup_warning.py
  deebot_client/commands/json/multimap_state.py
  deebot_client/commands/json/network.py
  deebot_client/commands/json/ota.py
  deebot_client/commands/json/play_sound.py
  deebot_client/commands/json/pos.py
  deebot_client/commands/json/relocation.py
  deebot_client/commands/json/safe_protect.py
  deebot_client/commands/json/stats.py
  deebot_client/commands/json/sweep_mode.py
  deebot_client/commands/json/true_detect.py
  deebot_client/commands/json/voice_assistant_state.py
  deebot_client/commands/json/volume.py
  deebot_client/commands/json/water_info.py
  deebot_client/commands/json/work_mode.py
  deebot_client/commands/xml/__init__.py
  deebot_client/commands/xml/charge_state.py
  deebot_client/commands/xml/common.py
  deebot_client/commands/xml/error.py
  deebot_client/commands/xml/fan_speed.py
  deebot_client/commands/xml/pos.py
  deebot_client/commands/xml/stats.py
  deebot_client/message.py
  deebot_client/messages/json/__init__.py
  deebot_client/messages/json/battery.py
  deebot_client/messages/json/map.py
  deebot_client/messages/json/stats.py
  deebot_client/util/__init__.py
  tests/commands/json/__init__.py
  tests/commands/json/test_clean_log.py
  tests/commands/json/test_common.py
  tests/test_command.py
  tests/test_mqtt_client.py
Labels: pr: refactor

#575 Add XML command "GetLifeSpan"
  deebot_client/commands/xml/__init__.py
  deebot_client/commands/xml/life_span.py
  deebot_client/events/__init__.py
  tests/commands/xml/test_life_span.py
Labels: pr: new-feature

#703 Add support for DEEBOT X1e OMNI (bro5wu)
  deebot_client/hardware/deebot/bro5wu.py
Labels: pr: enhancement

#689 Add DEEBOT N8 Pro Care (s1f8g7)
  deebot_client/hardware/deebot/s1f8g7.py
Labels: pr: new-feature

#705 Fix LifeSpan enum
  deebot_client/events/__init__.py
  tests/events/test_events.py
Labels: pr: bugfix

#603 Add auto empty message and commands
  deebot_client/capabilities.py
  deebot_client/commands/json/__init__.py
  deebot_client/commands/json/auto_empty.py
  deebot_client/commands/json/common.py
  deebot_client/commands/json/ota.py
  deebot_client/events/__init__.py
  deebot_client/events/auto_empty.py
  deebot_client/hardware/deebot/p95mgv.py
  deebot_client/hardware/deebot/qhe2o2.py
  deebot_client/messages/json/__init__.py
  deebot_client/messages/json/auto_empty.py
  pyproject.toml
  tests/commands/json/test_auto_empty.py
  tests/hardware/test_init.py
  tests/messages/json/test_auto_empty.py
Labels: pr: new-feature

#708 Fix N20 Pro auto empty
  deebot_client/hardware/deebot/qhe2o2.py
Labels: pr: bugfix

#645 Add base station functions
  deebot_client/capabilities.py
  deebot_client/commands/__init__.py
  deebot_client/commands/json/__init__.py
  deebot_client/commands/json/station_action.py
  deebot_client/commands/json/station_state.py
  deebot_client/events/__init__.py
  deebot_client/events/base_station.py
  deebot_client/hardware/deebot/buom7k.py
  deebot_client/hardware/deebot/p95mgv.py
  deebot_client/hardware/deebot/qhe2o2.py
  deebot_client/messages/json/__init__.py
  deebot_client/messages/json/station_state.py
  tests/commands/json/test_station_action.py
  tests/commands/json/test_station_state.py
  tests/hardware/test_init.py
  tests/messages/json/test_station_state.py
Labels: pr: new-feature

#715 Add DEEBOT X2 Omni Hight (DEEBOT X2 PRO)
  deebot_client/hardware/deebot/p7l7iu.py
Labels: pr: new-feature

#716 Added capabilities for DEEBOT T20 PRO `m4xnd8` similar to T20
  deebot_client/hardware/deebot/m4xnd8.py
Labels: pr: new-feature

#718 Rename EnableEvent property to enabled
  deebot_client/events/__init__.py
Labels: pr: Breaking Change

#709 Refactor station action
  deebot_client/capabilities.py
  deebot_client/commands/__init__.py
  deebot_client/commands/json/station_action.py
  deebot_client/events/__init__.py
  deebot_client/events/station.py
  deebot_client/hardware/deebot/buom7k.py
  deebot_client/hardware/deebot/p95mgv.py
  deebot_client/hardware/deebot/qhe2o2.py
  deebot_client/messages/json/station_state.py
  tests/commands/json/test_station_action.py
  tests/commands/json/test_station_state.py
  tests/hardware/test_init.py
  tests/messages/json/test_station_state.py
Labels: pr: Breaking Change, pr: refactor

#719 Fix left over after renameing base station to station
  deebot_client/capabilities.py
  deebot_client/events/__init__.py
  deebot_client/hardware/deebot/buom7k.py
  deebot_client/hardware/deebot/p95mgv.py
  deebot_client/hardware/deebot/qhe2o2.py
Labels: pr: Breaking Change
