Repository DeebotUniverse/client.py, pull requests merged in 2024-02, with the labels that each got.

#388 Add 'Mop-Only' commands and event
  deebot_client/capabilities.py
  deebot_client/commands/json/__init__.py
  deebot_client/commands/json/common.py
  deebot_client/commands/json/sweep_mode.py
  deebot_client/events/__init__.py
  deebot_client/hardware/deebot/2o4lnm.py
  tests/commands/json/__init__.py
  tests/commands/json/test_sweep_mode.py
Labels: pr: new-feature

#415 Add get_ecovacs_country
  deebot_client/authentication.py
  deebot_client/util/continents.py
  deebot_client/util/countries.py
  requirements-test.txt
  tests/conftest.py
  tests/test_authentication.py
  tests/util/test_continents.py
  tests/util/test_countries.py
Labels: pr: bugfix

#418 Don't log twice on api timeout
  deebot_client/authentication.py
  deebot_client/command.py
  deebot_client/exceptions.py
  tests/test_command.py
Labels: pr: bugfix

#352 Add new command: "ClearMap"
  deebot_client/capabilities.py
  deebot_client/commands/json/__init__.py
  deebot_client/commands/json/clear_map.py
  deebot_client/hardware/deebot/yna5xi.py
Labels: pr: new-feature

#419 Get devices from GetDeviceList too
  deebot_client/api_client.py
  deebot_client/authentication.py
  deebot_client/const.py
  deebot_client/models.py
  tests/commands/__init__.py
  tests/conftest.py
Labels: pr: new-feature

#372 Add `GetMapSetV2` command
  deebot_client/commands/json/__init__.py
  deebot_client/commands/json/map.py
  deebot_client/hardware/deebot/p95mgv.py
  deebot_client/map.py
  deebot_client/messages/json/__init__.py
  deebot_client/messages/json/map.py
  deebot_client/util/__init__.py
  tests/commands/json/test_map.py
  tests/messages/json/test_map.py
Labels: pr: new-feature

#348 Add "Ota" commands
  deebot_client/capabilities.py
  deebot_client/commands/json/__init__.py
  deebot_client/commands/json/ota.py
  deebot_client/events/__init__.py
  deebot_client/hardware/deebot/p95mgv.py
  deebot_client/hardware/deebot/yna5xi.py
  tests/commands/json/test_ota.py
  tests/hardware/test_init.py
Labels: pr: new-feature

#424 Update ruff & yamllint
  .pre-commit-config.yaml
  deebot_client/command.py
  deebot_client/commands/json/charge_state.py
  deebot_client/commands/json/volume.py
  deebot_client/commands/json/water_info.py
  pyproject.toml
  tests/fixtures/base.py
Labels: pr: dependency-update

#425 Add model back
  deebot_client/models.py
Labels: pr: bugfix

#435 Add device type
  deebot_client/hardware/deebot/2o4lnm.py
  deebot_client/hardware/deebot/fallback.py
  deebot_client/hardware/deebot/p1jij8.py
  deebot_client/hardware/deebot/p95mgv.py
  deebot_client/hardware/deebot/umwv6z.py
  deebot_client/hardware/deebot/x5d34r.py
  deebot_client/hardware/deebot/yna5xi.py
  deebot_client/models.py
  tests/hardware/test_init.py
  tests/helpers/__init__.py
Labels: pr: new-feature

#431 Nitpicks text
  README.md
  deebot_client/authentication.py
  deebot_client/capabilities.py
  deebot_client/event_bus.py
  deebot_client/events/efficiency_mode.py
  deebot_client/hardware/deebot/2o4lnm.py
  deebot_client/hardware/deebot/fallback.py
  deebot_client/hardware/deebot/p1jij8.py
  deebot_client/hardware/deebot/p95mgv.py
  deebot_client/hardware/deebot/x5d34r.py
  deebot_client/hardware/deebot/yna5xi.py
  deebot_client/map.py
  deebot_client/models.py
  deebot_client/mqtt_client.py
  deebot_client/util/__init__.py
  deebot_client/util/continents.py
  tests/commands/json/test_common.py
  tests/commands/json/test_efficiency.py
  tests/helpers/tasks.py
  tests/messages/json/test_map.py
  tests/test_authentication.py
  tests/test_device.py
  tests/test_event_bus.py
  tests/test_mqtt_client.py
  tests/util/test_continents.py
Labels: pr: Breaking Change, pr: refactor

#436 Fix CI
  deebot_client/hardware/deebot/umwv6z.py
Labels: pr: bugfix

#439 Replace DeviceType by own capability class per device type
  deebot_client/capabilities.py
  deebot_client/hardware/deebot/2o4lnm.py
  deebot_client/hardware/deebot/5xu9h3.py
  deebot_client/hardware/deebot/fallback.py
  deebot_client/hardware/deebot/p1jij8.py
  deebot_client/hardware/deebot/p95mgv.py
  deebot_client/hardware/deebot/umwv6z.py
  deebot_client/hardware/deebot/x5d34r.py
  deebot_client/hardware/deebot/yna5xi.py
  deebot_client/models.py
  tests/hardware/test_init.py
  tests/helpers/__init__.py
Labels: pr: new-feature

#440 Refactor due capabilities typing
  deebot_client/api_client.py
  deebot_client/capabilities.py
  deebot_client/command.py
  deebot_client/commands/json/clean.py
  deebot_client/commands/json/clean_logs.py
  deebot_client/device.py
  deebot_client/hardware/deebot/__init__.py
  deebot_client/models.py
  deebot_client/mqtt_client.py
  tests/commands/__init__.py
  tests/commands/json/__init__.py
  tests/commands/json/test_clean.py
  tests/commands/json/test_common.py
  tests/commands/xml/__init__.py
  tests/commands/xml/test_error.py
  tests/conftest.py
  tests/hardware/test_init.py
  tests/helpers/__init__.py
  tests/mqtt_util.py
  tests/test_command.py
  tests/test_device.py
  tests/test_mqtt_client.py
  tests/test_mqtt_client_reconnect.py
Labels: pr: Breaking Change, pr: refactor
