Repository DeebotUniverse/client.py, pull requests merged in 2024-09, with the labels that each got.

#561 Add XML command "GetCleanSum"
  deebot_client/commands/xml/__init__.py
  deebot_client/commands/xml/stats.py
  tests/commands/xml/test_stats.py
Labels: pr: new-feature

#564 Use uv instead of pip
  .devcontainer.json
  .github/workflows/ci.yml
  .github/workflows/python-publish.yml
  .pre-commit-config.yaml
  .python-version
  pyproject.toml
  uv.lock
Labels: pr: refactor

#565 Fix release workflow
  pyproject.toml
  uv.lock
Labels: pr: bugfix

#566 Replace dependabot with renovate and clean up missed files
  .devcontainer.json
  .github/dependabot.yml
  .github/renovate.json
  requirements-dev.txt
  requirements-test.txt
  requirements.txt
Labels: pr: refactor

#571 Use uv build
  .github/workflows/ci.yml
  .github/workflows/python-publish.yml
  pyproject.toml
  uv.lock
Labels: pr: refactor

#572 Optimize github actions
  .github/workflows/ci.yml
  .github/workflows/python-publish.yml
Labels: pr: refactor
