Repository DeebotUniverse/client.py, pull requests merged in 2025-01, with the labels that each got.

#731 Added support for N20e
  deebot_client/hardware/deebot/zgsvkq.py
Labels: pr: new-feature

#729 Add .local/bin to devcontainer path to fix uv
  .devcontainer.json
Labels: pr: bugfix

#725 Add DEEBOT T8 AIVI + (vdehg6)
  deebot_client/hardware/deebot/vdehg6.py
Labels: pr: new-feature

#723 Move decompress_7z_base64_data to rust
  .devcontainer.json
  .github/renovate.json
  .github/workflows/ci.yml
  .github/workflows/python-publish.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  deebot_client/commands/json/map.py
  deebot_client/map.py
  deebot_client/rs.pyi
  deebot_client/util/__init__.py
  pyproject.toml
  scripts/setup.sh
  src/lib.rs
  tests/commands/json/test_map.py
  tests/test_map.py
  tests/test_rs.py
  uv.lock
Labels: pr: enhancement

#739 Add DEEBOT X1 PRO OMNI (s523z1) support
  deebot_client/hardware/deebot/s523z1.py
Labels: pr: new-feature

#745 Added support for Deebot U2 (ipzjy0) via symlink
  deebot_client/hardware/deebot/ipzjy0.py
Labels: pr: new-feature

#752 Add support for Deebot U2 (ts2ofl)
  deebot_client/hardware/deebot/ts2ofl.py
Labels: pr: new-feature

#749 Add DEEBOT T10 OMNI (yi396x) support
  deebot_client/hardware/deebot/yi396x.py
Labels: pr: new-feature

#758 Unignore ruff rule ISC001 as it no longer collides with the formatter in ruff 0.9.1
  pyproject.toml
Labels: pr: refactor

#763 add missing t30s combo vacuums
  deebot_client/hardware/deebot/ee23uv.py
  deebot_client/hardware/deebot/ue8kcc.py
Labels: pr: new-feature

#574 Add XML command "PlaySound"
  deebot_client/commands/xml/__init__.py
  deebot_client/commands/xml/common.py
  deebot_client/commands/xml/play_sound.py
  tests/commands/xml/test_play_sound.py
Labels: pr: new-feature

#765 Fix decompress_7z_base64_data
  deebot_client/commands/json/map.py
  deebot_client/map.py
  deebot_client/rs.pyi
  src/lib.rs
  tests/test_map.py
  tests/test_rs.py
Labels: pr: bugfix

#767 Use dependencies groups
  .devcontainer.json
  .github/workflows/ci.yml
  pyproject.toml
  scripts/setup.sh
  uv.lock
Labels: pr: refactor

#768 Add test for the svg map
  deebot_client/map.py
  tests/test_map.py
Labels: pr: enhancement

#772 Use real life map for better performance testing
  tests/test_map.py
Labels: pr: refactor

#775 Move extracting of trace points to rust
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  deebot_client/map.py
  deebot_client/rs.pyi
  src/lib.rs
  tests/test_map.py
Labels: pr: refactor

#776 Refactor rust code to submodules
  deebot_client/commands/json/map.py
  deebot_client/map.py
  deebot_client/rs/map.pyi
  deebot_client/rs/util.pyi
  pyproject.toml
  src/lib.rs
  src/map.rs
  src/util.rs
  tests/rs/__init__.py
  tests/rs/test_util.py
  tests/test_map.py
Labels: pr: refactor

#778 Use different lzma crate without liblzma-dev dependency
  .github/workflows/ci.yml
  .github/workflows/python-publish.yml
  Cargo.lock
  Cargo.toml
  scripts/setup.sh
  src/util.rs
Labels: pr: refactor

#780 Improve submodule registration in rust
  src/lib.rs
Labels: pr: refactor

#779 Fix MQTT subscribe topics
  deebot_client/device.py
  deebot_client/mqtt_client.py
  tests/mqtt_util.py
  tests/test_mqtt_client.py
  tests/test_mqtt_client_reconnect.py
Labels: pr: bugfix

#783 Add T30S Class eqmf84
  deebot_client/hardware/deebot/eqmf84.py
Labels: pr: new-feature

#759 Use a single workflow for CI and release & build and test more wheels
  .github/workflows/ci.yml
  .github/workflows/python-publish.yml
  ci/Dockerfile.alpine
  ci/entrypoint.sh
  pyproject.toml
  pytest.ini
  scripts/run-in-env.sh
  scripts/setup.sh
  tests/test_map.py
  tests/test_mqtt_client.py
  tests/test_mqtt_client_reconnect.py
  uv.lock
Labels: pr: refactor

#788 Fix release
  .github/workflows/ci.yml
Labels: pr: bugfix

#789 Codspeed doesn't support release pipeline
  .github/workflows/ci.yml
Labels: pr: bugfix

#791 Fix rust clippy findings
  src/lib.rs
  src/map.rs
  src/util.rs
Labels: pr: refactor

#792 Add 5 devices by similarity
  deebot_client/hardware/deebot/8tyt2y.py
  deebot_client/hardware/deebot/9gqyaq.py
  deebot_client/hardware/deebot/kr9c86.py
  deebot_client/hardware/deebot/rvo6ev.py
  deebot_client/hardware/deebot/wlqdkp.py
Labels: pr: new-feature

#794 Add support for T9 Power
  deebot_client/hardware/deebot/dqcneu.py
Labels: pr: new-feature

#777 Move svg generation to rust
  .devcontainer.json
  Cargo.lock
  Cargo.toml
  deebot_client/map.py
  deebot_client/rs/map.pyi
  pyproject.toml
  scripts/setup.sh
  src/lib.rs
  src/map.rs
  tests/test_map.py
  uv.lock
Labels: pr: refactor
