Repository DeebotUniverse/client.py, pull requests merged in 2025-09, with the labels that each got.

#1100 Add WaterCustomAmountEvent and updated water capability
  deebot_client/capabilities.py
  deebot_client/commands/json/water_info.py
  deebot_client/events/water_info.py
  deebot_client/hardware/deebot/xco2fc.py
  tests/commands/json/test_water_info.py
Labels: pr: new-feature, pr: Breaking Change

#1103 Log device class on some command log entries
  deebot_client/command.py
Labels: pr: enhancement

#1161 Fix bugs introduced with #1103
  deebot_client/command.py
  tests/test_command.py
Labels: pr: bugfix

#1147 Add support for WorkState messages/commands
  deebot_client/commands/json/work_state.py
  deebot_client/events/station.py
  deebot_client/hardware/deebot/ilt3k8.py
  deebot_client/messages/json/__init__.py
  deebot_client/messages/json/work_state.py
  tests/commands/json/test_work_state.py
  tests/messages/__init__.py
  tests/messages/json/test_work_state.py
Labels: pr: new-feature

#1167 GetWorkState support for X8 Pro Omni (n0vyif)
  deebot_client/hardware/deebot/n0vyif.py
Labels: pr: refactor

#1169 Fix devcontainer
  .devcontainer.json
Labels: pr: bugfix

#1170 Add capabilities to the EventBus
  deebot_client/capabilities.py
  deebot_client/commands/json/map.py
  deebot_client/commands/xml/map.py
  deebot_client/device.py
  deebot_client/event_bus.py
  deebot_client/hardware/deebot/2o4lnm.py
  deebot_client/hardware/deebot/2pv572.py
  deebot_client/hardware/deebot/4bdkrs.py
  deebot_client/hardware/deebot/7bryc5.py
  deebot_client/hardware/deebot/8kwdb4.py
  deebot_client/hardware/deebot/9eamof.py
  deebot_client/hardware/deebot/9s1s80.py
  deebot_client/hardware/deebot/b2jqs4.py
  deebot_client/hardware/deebot/buom7k.py
  deebot_client/hardware/deebot/co3fyu.py
  deebot_client/hardware/deebot/e6ofmn.py
  deebot_client/hardware/deebot/ee23uv.py
  deebot_client/hardware/deebot/kr0277.py
  deebot_client/hardware/deebot/m1wkuw.py
  deebot_client/hardware/deebot/n0vyif.py
  deebot_client/hardware/deebot/p1jij8.py
  deebot_client/hardware/deebot/p7l7iu.py
  deebot_client/hardware/deebot/p95mgv.py
  deebot_client/hardware/deebot/qhe2o2.py
  deebot_client/hardware/deebot/ue8kcc.py
  deebot_client/hardware/deebot/umwv6z.py
  deebot_client/hardware/deebot/x5d34r.py
  deebot_client/hardware/deebot/xco2fc.py
  deebot_client/hardware/deebot/yna5xi.py
  tests/commands/__init__.py
  tests/commands/json/__init__.py
  tests/commands/json/test_map.py
  tests/commands/xml/__init__.py
  tests/commands/xml/test_battery.py
  tests/commands/xml/test_charge.py
  tests/commands/xml/test_charge_state.py
  tests/commands/xml/test_clean.py
  tests/commands/xml/test_clean_logs.py
  tests/commands/xml/test_clean_speed.py
  tests/commands/xml/test_error.py
  tests/commands/xml/test_life_span.py
  tests/commands/xml/test_map.py
  tests/commands/xml/test_play_sound.py
  tests/commands/xml/test_pos.py
  tests/commands/xml/test_stats.py
  tests/conftest.py
  tests/test_device.py
  tests/test_event_bus.py
Labels: pr: Breaking Change, pr: refactor

#1165 Update Cababilities for Deebot 500
  deebot_client/hardware/deebot/r8ead0.py
Labels: pr: enhancement

#1179 Add devices by similarity
  deebot_client/hardware/deebot/36hdj8.py
  deebot_client/hardware/deebot/6q3rfp.py
  deebot_client/hardware/deebot/gcu5tt.py
  deebot_client/hardware/deebot/kl54s5.py
  deebot_client/hardware/deebot/npu3pt.py
  deebot_client/hardware/deebot/y72606.py
Labels: pr: new-feature

#1182 Handle new MapSetV2 data format
  deebot_client/commands/json/map.py
  tests/commands/json/test_map.py
Labels: pr: enhancement

#1188 Add setMajorMap and onMajorMap
  deebot_client/capabilities.py
  deebot_client/commands/json/__init__.py
  deebot_client/commands/json/map/__init__.py
  deebot_client/commands/json/map/major_map.py
  deebot_client/hardware/2o4lnm.py
  deebot_client/hardware/4bdkrs.py
  deebot_client/hardware/7bryc5.py
  deebot_client/hardware/8kwdb4.py
  deebot_client/hardware/9eamof.py
  deebot_client/hardware/9s1s80.py
  deebot_client/hardware/b2jqs4.py
  deebot_client/hardware/buom7k.py
  deebot_client/hardware/co3fyu.py
  deebot_client/hardware/e6ofmn.py
  deebot_client/hardware/ee23uv.py
  deebot_client/hardware/kr0277.py
  deebot_client/hardware/m1wkuw.py
  deebot_client/hardware/n0vyif.py
  deebot_client/hardware/p1jij8.py
  deebot_client/hardware/p7l7iu.py
  deebot_client/hardware/p95mgv.py
  deebot_client/hardware/qhe2o2.py
  deebot_client/hardware/ue8kcc.py
  deebot_client/hardware/umwv6z.py
  deebot_client/hardware/x5d34r.py
  deebot_client/hardware/xco2fc.py
  deebot_client/hardware/yna5xi.py
  deebot_client/messages/__init__.py
  deebot_client/messages/json/__init__.py
  deebot_client/messages/json/map.py
  tests/commands/json/map/__init__.py
  tests/commands/json/map/test_init.py
  tests/commands/json/map/test_major_map.py
  tests/messages/__init__.py
  tests/messages/json/test_map.py
Labels: pr: new-feature

#1189 Refactor CachedMapInfoEvent and add OnCachedMapInfo
  deebot_client/commands/json/map/__init__.py
  deebot_client/commands/json/map/cached_map_info.py
  deebot_client/commands/json/map/major_map.py
  deebot_client/commands/xml/map.py
  deebot_client/events/map.py
  deebot_client/messages/__init__.py
  deebot_client/messages/json/__init__.py
  deebot_client/messages/json/map/__init__.py
  deebot_client/messages/json/map/cached_map_info.py
  tests/commands/json/map/test_cached_map_info.py
  tests/commands/json/map/test_init.py
  tests/commands/xml/test_map.py
  tests/data/map/test_1.py
  tests/messages/__init__.py
  tests/messages/json/map/__init__.py
  tests/messages/json/map/test_cached_map_info.py
  tests/messages/json/map/test_init.py
Labels: pr: Breaking Change, pr: refactor

#1191 Add map test with virtual walls
  .pre-commit-config.yaml
  tests/data/map/test_2.py
Labels: pr: enhancement
