Repository DeebotUniverse/client.py, pull requests merged in 2025-04, with the labels that each got.

#893 Add legacy GetNetInfo JSON command
  deebot_client/commands/json/__init__.py
  deebot_client/commands/json/network.py
  deebot_client/message.py
  tests/commands/json/test_network.py
Labels: pr: new-feature

#906 XML Battery Commands
  deebot_client/commands/xml/__init__.py
  deebot_client/commands/xml/battery.py
  tests/commands/xml/test_battery.py
Labels: pr: new-feature

#900 Add XML Message BatteryInfo
  deebot_client/messages/__init__.py
  deebot_client/messages/xml/__init__.py
  deebot_client/messages/xml/battery.py
  deebot_client/messages/xml/common.py
  tests/messages/__init__.py
  tests/messages/xml/__init__.py
  tests/messages/xml/test_battery.py
  tests/messages/xml/test_common.py
Labels: pr: new-feature

#907 Add classes to convert standard enums into XML values
  deebot_client/events/__init__.py
  deebot_client/events/fan_speed.py
  deebot_client/models.py
  deebot_client/util/enum.py
  tests/events/test_events.py
  tests/events/test_fan_speed.py
  tests/test_models.py
  tests/util/test_enum.py
Labels: pr: refactor

#910 Implement XML Command GetCleanLogs
  deebot_client/commands/xml/__init__.py
  deebot_client/commands/xml/clean_logs.py
  tests/commands/xml/test_clean_logs.py
Labels: pr: new-feature

#916 Implement XML Position messages
  deebot_client/commands/xml/__init__.py
  deebot_client/commands/xml/pos.py
  deebot_client/messages/xml/__init__.py
  deebot_client/messages/xml/pos.py
  tests/commands/xml/test_pos.py
  tests/messages/xml/test_pos.py
Labels: pr: new-feature

#917 Split WaterInfoEvent into multiple
  deebot_client/capabilities.py
  deebot_client/commands/json/water_info.py
  deebot_client/events/__init__.py
  deebot_client/events/base.py
  deebot_client/events/water_info.py
  deebot_client/hardware/deebot/2o4lnm.py
  deebot_client/hardware/deebot/4bdkrs.py
  deebot_client/hardware/deebot/7bryc5.py
  deebot_client/hardware/deebot/7j1tu6.py
  deebot_client/hardware/deebot/8kwdb4.py
  deebot_client/hardware/deebot/9s1s80.py
  deebot_client/hardware/deebot/b2jqs4.py
  deebot_client/hardware/deebot/buom7k.py
  deebot_client/hardware/deebot/e6ofmn.py
  deebot_client/hardware/deebot/ee23uv.py
  deebot_client/hardware/deebot/kr0277.py
  deebot_client/hardware/deebot/m1wkuw.py
  deebot_client/hardware/deebot/p1jij8.py
  deebot_client/hardware/deebot/p7l7iu.py
  deebot_client/hardware/deebot/p95mgv.py
  deebot_client/hardware/deebot/qhe2o2.py
  deebot_client/hardware/deebot/ts2ofl.py
  deebot_client/hardware/deebot/ue8kcc.py
  deebot_client/hardware/deebot/umwv6z.py
  deebot_client/hardware/deebot/x5d34r.py
  deebot_client/hardware/deebot/xco2fc.py
  deebot_client/hardware/deebot/yna5xi.py
  tests/commands/json/__init__.py
  tests/commands/json/test_water_info.py
  tests/hardware/test_init.py
  tests/test_event_bus.py
Labels: pr: Breaking Change

#926 Add support for T8 AIVI+ (tpnwyu)
  deebot_client/hardware/deebot/tpnwyu.py
Labels: pr: new-feature

#911 Add XML command SetCleanSpeed
  deebot_client/commands/xml/__init__.py
  deebot_client/commands/xml/clean_speed.py
  tests/commands/xml/test_clean_speed.py
  tests/commands/xml/test_fan_speed.py
Labels: pr: new-feature

#909 Add XML Map commands
  .pre-commit-config.yaml
  deebot_client/commands/xml/__init__.py
  deebot_client/commands/xml/map.py
  tests/commands/xml/test_map.py
Labels: pr: new-feature

#915 Implement XML ChargeState messages
  deebot_client/commands/xml/charge_state.py
  deebot_client/messages/xml/__init__.py
  deebot_client/messages/xml/charge_state.py
  tests/messages/xml/test_charge_state.py
Labels: pr: new-feature

#908 Add XML Clean Commands
  deebot_client/commands/xml/__init__.py
  deebot_client/commands/xml/clean.py
  tests/commands/xml/test_clean.py
Labels: pr: new-feature

#898 Add minor map to map capabilities
  deebot_client/capabilities.py
  deebot_client/commands/json/map.py
  deebot_client/device.py
  deebot_client/hardware/deebot/2o4lnm.py
  deebot_client/hardware/deebot/4bdkrs.py
  deebot_client/hardware/deebot/7bryc5.py
  deebot_client/hardware/deebot/8kwdb4.py
  deebot_client/hardware/deebot/9s1s80.py
  deebot_client/hardware/deebot/b2jqs4.py
  deebot_client/hardware/deebot/buom7k.py
  deebot_client/hardware/deebot/e6ofmn.py
  deebot_client/hardware/deebot/ee23uv.py
  deebot_client/hardware/deebot/kr0277.py
  deebot_client/hardware/deebot/m1wkuw.py
  deebot_client/hardware/deebot/p1jij8.py
  deebot_client/hardware/deebot/p7l7iu.py
  deebot_client/hardware/deebot/p95mgv.py
  deebot_client/hardware/deebot/qhe2o2.py
  deebot_client/hardware/deebot/ue8kcc.py
  deebot_client/hardware/deebot/umwv6z.py
  deebot_client/hardware/deebot/x5d34r.py
  deebot_client/hardware/deebot/xco2fc.py
  deebot_client/hardware/deebot/yna5xi.py
  deebot_client/map.py
  tests/conftest.py
  tests/test_device.py
  tests/test_map.py
Labels: pr: Breaking Change

#895 Implement XML Command ResetLifeSpan
  deebot_client/command.py
  deebot_client/commands/__init__.py
  deebot_client/commands/xml/__init__.py
  deebot_client/commands/xml/common.py
  deebot_client/commands/xml/life_span.py
  tests/commands/xml/__init__.py
  tests/commands/xml/test_common.py
  tests/commands/xml/test_life_span.py
Labels: pr: new-feature

#931 Remove duplicate code for COMMANDS_WITH_MQTT_P2P_HANDLING
  deebot_client/commands/__init__.py
  deebot_client/commands/json/__init__.py
  deebot_client/commands/xml/__init__.py
Labels: pr: refactor

#932 Fix water info events
  deebot_client/events/water_info.py
Labels: pr: bugfix

#935 Fix XML Bots and add FirmwareEvent
  deebot_client/commands/json/network.py
  deebot_client/device.py
  deebot_client/events/__init__.py
  deebot_client/message.py
  tests/commands/json/__init__.py
  tests/commands/json/test_advanced_mode.py
  tests/commands/json/test_auto_empty.py
  tests/commands/json/test_battery.py
  tests/commands/json/test_border_switch.py
  tests/commands/json/test_carpet.py
  tests/commands/json/test_charge.py
  tests/commands/json/test_charge_state.py
  tests/commands/json/test_child_lock.py
  tests/commands/json/test_clean.py
  tests/commands/json/test_clean_count.py
  tests/commands/json/test_clean_preference.py
  tests/commands/json/test_continuous_cleaning.py
  tests/commands/json/test_cross_map_border_warning.py
  tests/commands/json/test_custom.py
  tests/commands/json/test_cut_direction.py
  tests/commands/json/test_efficiency.py
  tests/commands/json/test_error.py
  tests/commands/json/test_fan_speed.py
  tests/commands/json/test_life_span.py
  tests/commands/json/test_map.py
  tests/commands/json/test_moveup_warning.py
  tests/commands/json/test_mulitmap_state.py
  tests/commands/json/test_network.py
  tests/commands/json/test_ota.py
  tests/commands/json/test_pos.py
  tests/commands/json/test_safe_protect.py
  tests/commands/json/test_station_state.py
  tests/commands/json/test_sweep_mode.py
  tests/commands/json/test_true_detect.py
  tests/commands/json/test_voice_assistant_state.py
  tests/commands/json/test_volume.py
  tests/commands/json/test_water_info.py
  tests/commands/json/test_work_mode.py
  tests/helpers/__init__.py
  tests/messages/__init__.py
  tests/messages/json/test_auto_empty.py
  tests/messages/json/test_battery.py
  tests/messages/json/test_station_state.py
  tests/messages/json/test_stats.py
  tests/test_device.py
  tests/test_message.py
Labels: pr: new-feature, pr: bugfix
