Repository DeebotUniverse/client.py, pull requests merged in 2025-02, with the labels that each got.

#798 Run cargo tests in CI
  .github/workflows/ci.yml
  ci/entrypoint.sh
  pyproject.toml
Labels: pr: refactor

#773 Goodbye Python 3.12
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  pyproject.toml
  uv.lock
Labels: pr: Breaking Change

#800 Create more musllinux wheels
  .github/workflows/ci.yml
  ci/Dockerfile.alpine
  tests/test_map.py
Labels: pr: new-feature

#802 Move map trace points and PositionType to rust
  deebot_client/commands/json/pos.py
  deebot_client/commands/xml/pos.py
  deebot_client/device.py
  deebot_client/events/__init__.py
  deebot_client/events/map.py
  deebot_client/map.py
  deebot_client/rs/map.pyi
  src/map.rs
  tests/commands/json/test_pos.py
  tests/commands/xml/test_pos.py
  tests/test_map.py
Labels: pr: refactor

#806 Add support for Deebot T30S Care (63cum9)
  deebot_client/hardware/deebot/63cum9.py
Labels: pr: new-feature

#807 Add tests to improve test coverage
  .codecov.yml
  src/map.rs
  tests/rs/test_util.py
Labels: pr: enhancement

#810 Add support for T8 Power (no61kx)
  deebot_client/hardware/deebot/no61kx.py
Labels: pr: new-feature

#812 Add support to decompress zstd
  Cargo.lock
  Cargo.toml
  deebot_client/commands/json/map.py
  deebot_client/map.py
  deebot_client/rs/util.pyi
  src/map.rs
  src/util.rs
  tests/rs/test_util.py
Labels: pr: new-feature, pr: bugfix

#813 Add XML charge command
  deebot_client/commands/xml/__init__.py
  deebot_client/commands/xml/charge.py
  tests/commands/xml/test_charge.py
Labels: pr: new-feature

#820 Prepare mqtt p2p for different data types
  deebot_client/command.py
  deebot_client/commands/json/common.py
  deebot_client/commands/json/life_span.py
  deebot_client/message.py
  deebot_client/mqtt_client.py
  tests/commands/json/__init__.py
  tests/commands/json/test_life_span.py
  tests/test_command.py
  tests/test_mqtt_client.py
Labels: pr: refactor

#818 Refactor MajorMapEvent
  deebot_client/commands/json/map.py
  deebot_client/events/map.py
  deebot_client/map.py
  pyproject.toml
  tests/commands/json/test_map.py
  tests/test_map.py
Labels: pr: refactor

#824 Add support for deebot-10 (yaj7uz)
  deebot_client/hardware/deebot/yaj7uz.py
Labels: pr: new-feature

#827 Fix Deebot T10 (jtmf04) capabilities
  deebot_client/hardware/deebot/jtmf04.py
Labels: pr: bugfix

#837 Simplify positions
  deebot_client/map.py
  tests/test_map.py
Labels: pr: refactor
