Repository DeebotUniverse/client.py, pull requests merged in 2025-03, with the labels that each got.

#838 Move png map genration to rust
  Cargo.lock
  Cargo.toml
  deebot_client/map.py
  deebot_client/rs/map.pyi
  deebot_client/util/__init__.py
  src/map.rs
  tests/test_map.py
Labels: pr: enhancement

#840 Remove unused dependencies
  pyproject.toml
  uv.lock
Labels: pr: bugfix

#870 Add support for GOAT O500 Panorama (300lc5)
  deebot_client/hardware/deebot/300lc5.py
Labels: pr: new-feature
