Repository DeebotUniverse/client.py, pull requests merged in 2025-05, with the labels that each got.

#929 Implement XML Map messages
  deebot_client/messages/xml/__init__.py
  deebot_client/messages/xml/map.py
  tests/messages/xml/test_map.py
Labels: pr: new-feature

#940 Add support for T50 Omni Pro (elrxgb)
  deebot_client/hardware/deebot/elrxgb.py
Labels: pr: new-feature

#943 Add support for T50 Pro (cuoipb) and DEEBOT T8 AIVI + (34vhpm) by similarity
  .gitignore
  deebot_client/hardware/deebot/34vhpm.py
  deebot_client/hardware/deebot/cuoipb.py
  scripts/check_for_similar_models.py
Labels: pr: new-feature

#930 Add XML Clean Messages
  deebot_client/commands/xml/clean.py
  deebot_client/messages/xml/__init__.py
  deebot_client/messages/xml/clean.py
  tests/commands/xml/test_clean.py
  tests/messages/__init__.py
  tests/messages/xml/test_clean.py
Labels: pr: new-feature

#954 Add support for DEEBOT OZMO 900 (y79a7u)
  deebot_client/hardware/deebot/y79a7u.py
Labels: pr: new-feature

#950 Add support for DEEBOT T50 MAX PRO OMNI (qnkybo)
  deebot_client/hardware/deebot/qnkybo.py
Labels: pr: new-feature

#955 Do not assume every PositionsEvent has a PositionType.DEEBOT inside
  deebot_client/device.py
  tests/test_device.py
Labels: pr: bugfix

#958 Remove dead code
  deebot_client/models.py
Labels: pr: refactor

#959 Fix CI deprecation warning
  .github/workflows/ci.yml
Labels: pr: refactor

#960 Added support for T50 Max Pro (c8rj4y)
  deebot_client/hardware/deebot/c8rj4y.py
Labels: pr: new-feature

#961 Add models by similarity by UILogicId
  .gitignore
  deebot_client/hardware/deebot/5089oy.py
  deebot_client/hardware/deebot/6cibhb.py
  deebot_client/hardware/deebot/7c26ui.py
  deebot_client/hardware/deebot/8o3xke.py
  deebot_client/hardware/deebot/9rft3c.py
  deebot_client/hardware/deebot/ao7fpw.py
  deebot_client/hardware/deebot/aqdd5p.py
  deebot_client/hardware/deebot/bheggm.py
  deebot_client/hardware/deebot/czjwet.py
  deebot_client/hardware/deebot/k1lgm7.py
  deebot_client/hardware/deebot/m17zko.py
  deebot_client/hardware/deebot/p1wg05.py
  deebot_client/hardware/deebot/qhq6i0.py
  deebot_client/hardware/deebot/ruhc0q.py
  deebot_client/hardware/deebot/sa4tf7.py
  deebot_client/hardware/deebot/wgxm70.py
  deebot_client/hardware/deebot/xztz07.py
  deebot_client/hardware/deebot/zjna8m.py
  scripts/check_for_similar_models.py
Labels: pr: new-feature

#949 Add initial support for Goat A1600 RTK (#852)
  deebot_client/hardware/deebot/xmp9ds.py
Labels: pr: new-feature

#962 Fiy type can be missing on OnStats
  deebot_client/messages/json/stats.py
  tests/messages/json/test_stats.py
Labels: pr: bugfix

#963 Added support for Deebot X1 Omni China version (8onkgl)
  deebot_client/hardware/deebot/8onkgl.py
Labels: pr: new-feature

#956 XML ChargeState IDLE should not produce any events
  deebot_client/messages/xml/charge_state.py
  tests/commands/xml/test_charge_state.py
  tests/messages/xml/test_charge_state.py
Labels: pr: bugfix

#982 Fix xml custom coordinates cleaning command
  deebot_client/commands/xml/clean.py
  tests/commands/json/test_clean.py
  tests/commands/xml/test_clean.py
Labels: pr: bugfix

#984 Fix empty data on MapTraceEvent and log input values of rust functions on error
  deebot_client/map.py
  src/map.rs
  src/util.rs
  tests/rs/test_map.py
  tests/test_map.py
Labels: pr: bugfix

#994 Add basic support for Goat A3000 (o4kvvk)
  deebot_client/hardware/deebot/o4kvvk.py
Labels: pr: new-feature
